### ISSUE TITLE
The shortcut just doesn't respond when I type something

### ISSUE THREAD

**Issue by Aymano200** [nicolodiamante/SiriGPT#2]

**Comment by nicolodiamante** [comment]
I see that you're having trouble with ChatGPT's shortcut. Can you please elaborate on the specific error you're facing? Are you receiving any error messages or is the shortcut completely unresponsive? Moreover, it would be beneficial to ensure that you have correctly entered the API Key and have not exceeded the token limit. Please provide me with more information so I can assist you better.

**Comment by Heratiki** [comment]
I'm having this issue as well. No matter what I say or do the shortcut completes without responding at all. 

I've tried nearly every configuration I can think of while setting it up and it still doesn't work. 

It should also be noted that outside of deleting the shortcut and downloading again there is no way to alter the initial setup parameters.

**Comment by nicolodiamante** [comment]
I think the problem lies in the lack of "Yes" or "No" values assigned in the text area used to decide where to store the API within the Data Jar. When launching the shortcut, if it does not find the API key either within Data Jar (if you use it, check if the path Key is correct) or within the shortcut (in the appropriate area where to paste it), the shortcut works but the lack of the API makes chatGPT not respond at all.

I leave you below a new link to download the shortcut, which I will also update on the README.
https://www.icloud.com/shortcuts/1150461dcd8b4e76b246f5e1e4fbcb14 

Please let me know if everything works or if you keep having problems.

**Comment by Aymano200** [comment]
How can I verify if I exceeded the token limit, I think the problem is here

**Comment by nicolodiamante** [comment]
You can check your current usage here: https://platform.openai.com/account/usage
I also leave you with a link to check all the rate limits: https://platform.openai.com/account/rate-limits
