### ISSUE TITLE
Siri 

### ISSUE THREAD

**Issue by edsonlima19** [nicolodiamante/SiriGPT#4]

**Comment by edsonlima19** [comment]
I’ve followed all steps to set SiriGPT shortcut, but, when I ask, it doesn't respond. I receive a page with Cancel and OK, then I receive a page where can see only 
![IMG_2520](https://github.com/nicolodiamante/SiriGPT/assets/8243441/55be33a8-ff1e-4c0d-9908-e8d0d6ae27e8)
![IMG_2519](https://github.com/nicolodiamante/SiriGPT/assets/8243441/dee67c03-19b6-4773-8e72-f0b15c7836a5)
the three options: Which one ?, Ask again and Done

**Comment by nicolodiamante** [comment]
Hello, apologies for the delay. I have made some changes to the shortcut. You can download the updated version [here](https://www.icloud.com/shortcuts/2fcd43bfad0b4d4daf5f0039e3cf44cf).

If you are using DataJar, please double-check if you have made any changes to the path or if there are any mismatches between where your API is located. If you choose to keep your API within the shortcut, make sure you've entered "No" in the first step of the settings and verified that your API is accurate.

If the error persists, it could be due to your API. If you have a free account, please check if you have reached the maximum number of tokens available [here](https://platform.openai.com/account/usage).

Another possible issue that another user encountered was the lack of voice response from Siri. If this happens, please check the Siri Settings to see if you have accidentally set it to answer you silently.

**Comment by edsonlima19** [comment]
Hello.

Thank you so much for your answer .
I tried in Portuguese (my first language), but Chatty didn't respond with
voice. it just presented the prompt. Then I changed my iPhone language and
Chatty responded with “what can I do for you today”, but when I asked I
got: “Request Error. Template “gpt-4” does not exist.

I hope your chat to work for everyone

Best Regards

Edson


Em ter., 16 de mai. de 2023 às 21:16, Nicolò Diamante <
***@***.***> escreveu:

**Comment by nicolodiamante** [comment]
Hi, I have updated the language detection so that SiriGPT should now start in Português if your iPhone is set in this language. 

You can download the version with the updated language detection [here](https://www.icloud.com/shortcuts/875590cb6f4440ca81ef935ce0e1d2b0).

However, when using the latest model version GPT-4, you may experience errors such as "The model: GPT-4 does not exist". This is because GPT-4 is currently in a limited beta and not everyone, even if they are on a paid plan, has access to the GPT-4 API. To gain access, you need to [join a waitlist here](
https://openai.com/waitlist/gpt-4-api) to receive an invitation. Developers seem to be given priority, and it is unclear when people who are not developers will be able to access it. If you do not have GPT-4 qualifications, it is recommended to use the GPT-3.5-Turbo model instead.


Let me know if the issue persists.


kind Regards
Nico

**Comment by edsonlima19** [comment]
Hi Nico.

Thanks for the answer.
I pay for the gpt-4 template and i received the plugins today.
I keep getting the message that gpt-4 doesn't exist.
Do I need to do anything else?

kind regards

Edson

**Comment by nicolodiamante** [comment]
I suggest you regenerate a new API Key to try to solve the problem.

Let me know if the issue persists.
Nico
