### ISSUE TITLE
Error while running the shortcut 

### ISSUE THREAD

**Issue by Cla33ic** [nicolodiamante/SiriGPT#5]
I tried to run it for the first time, but I get an error when trying to run.

**Comment by nicolodiamante** [comment]
Hi, could you please give me more information about the kind of error you encounter?

If you are using DataJar, please double-check if you have made any changes to the path or if there are any mismatches between where your API is located. If instead, you have chosen to keep your API within the shortcut, make sure you've entered "No" in the first step of the settings and verify that your API Key is correct.

If the error persists, it could be due to your API. If you have a free account, please check if you have reached the maximum number of tokens available [here](https://platform.openai.com/account/usage).

I have updated SiriGPT, you can [download the new version here](https://www.icloud.com/shortcuts/875590cb6f4440ca81ef935ce0e1d2b0).

Keep in mind, when using the latest model version GPT-4, you may experience errors such as "The model: GPT-4 does not exist". This is because GPT-4 is currently in a limited beta and not everyone, even if they are on a paid plan, has access to the GPT-4 API. To gain access, you need to join a waitlist here to receive an invitation. Developers seem to be given priority, and it is unclear when people who are not developers will be able to access it. If you do not have GPT-4 qualifications, it is recommended to use the GPT-3.5-Turbo model instead.

Let me know if the issue persists.

**Comment by Cla33ic** [comment]
Seemed like there was an server sided issue with OpenAI works now.
